spring:
  application:
    name: catalog-service
  profiles:
    active: dev
  jpa:
    show-sql: true          # logs the SQL JPA generates
    properties:
      hibernate.format_sql: true
  mvc:
    problemdetails:
      enabled: true
server:
  port: 8080
bingewatch:
  errors:
    base-uri: https://bingewatch.dev/errors
